### ISSUE TITLE
hi please tell me where to run the code step by step

### ISSUE THREAD

**Issue by sagarvet** [raphaelcfernandes/Android-Battery-Saver#12]
please tell me where to run the code step by step i have vs studio please help me my insta :- @_sagar_vetal

**Comment by sagarvet** [comment]
please tell me where to run the code step by step i have vs studio please help me my insta :- @_sagar_vetal

**Comment by raphaelcfernandes** [comment]
Hi, it's been a while since I last touched it, but you will need an Android version that has root access so the app can read/write from the cpu files

**Comment by sagarvet** [comment]
I didn't understand but listen
I am a diploma student in our college they have been told to do one project
so do you have any other project

**Comment by raphaelcfernandes** [comment]
I'm not sure I'm following.... do you wanna copy my work and present as yours?

**Comment by sagarvet** [comment]
Yes
